### ISSUE TITLE
有错误

### ISSUE THREAD

**Issue by ziming2018** [jkchao/vue-admin#1]
运行错误

**Comment by jkchao** [comment]
@ziming2018 报错信息看下

**Comment by ziming2018** [comment]
> vue-blog@1.0.0 dev /home/ziming/123/vue-admin
> node build/dev-server.js

[HPM] Proxy created: /api  ->  http://localhost:8000
[HPM] Proxy rewrite rule created: "^api" ~> "/api"
> Starting dev server...


 ERROR  Failed to compile with 11 errors                                18:20:09

 error  in ./src/assets/scss/index.scss

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ziming/123/vue-admin/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:906:18)
    at Object.getInstalledBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ziming/123/vue-admin/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:612:30)

 @ ./src/assets/scss/index.scss 4:14-151 13:3-17:5 14:22-159
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/layout/App.vue

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ziming/123/vue-admin/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:906:18)
    at Object.getInstalledBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ziming/123/vue-admin/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:612:30)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7ceb9c48","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/layout/App.vue 4:14-392 13:3-17:5 14:22-400
 @ ./src/layout/App.vue
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/login.vue

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ziming/123/vue-admin/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:906:18)
    at Object.getInstalledBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ziming/123/vue-admin/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:612:30)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-44e4db64","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/pages/login.vue 4:14-394 13:3-17:5 14:22-402
 @ ./src/pages/login.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/index.vue

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ziming/123/vue-admin/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:906:18)
    at Object.getInstalledBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ziming/123/vue-admin/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:612:30)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-13e5ef37","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/pages/index.vue 4:14-394 13:3-17:5 14:22-402
 @ ./src/pages/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/article/index.vue

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ziming/123/vue-admin/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:906:18)
    at Object.getInstalledBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ziming/123/vue-admin/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:612:30)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-3130285e","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/pages/article/index.vue 4:14-406 13:3-17:5 14:22-414
 @ ./src/pages/article/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/article/release.vue

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ziming/123/vue-admin/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:906:18)
    at Object.getInstalledBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ziming/123/vue-admin/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:612:30)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-bd404fda","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/pages/article/release.vue 4:14-408 13:3-17:5 14:22-416
 @ ./src/pages/article/release.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/comments/index.vue

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ziming/123/vue-admin/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:906:18)
    at Object.getInstalledBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ziming/123/vue-admin/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:612:30)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-2e71a43c","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/pages/comments/index.vue 4:14-406 13:3-17:5 14:22-414
 @ ./src/pages/comments/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/tags/index.vue

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ziming/123/vue-admin/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:906:18)
    at Object.getInstalledBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ziming/123/vue-admin/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:612:30)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-61fbbb47","scoped":true,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/pages/tags/index.vue 4:14-405 13:3-17:5 14:22-413
 @ ./src/pages/tags/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/heros/index.vue

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ziming/123/vue-admin/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:906:18)
    at Object.getInstalledBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ziming/123/vue-admin/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:612:30)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-5bb5c2a1","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/pages/heros/index.vue 4:14-406 13:3-17:5 14:22-414
 @ ./src/pages/heros/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/pages/set/index.vue

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ziming/123/vue-admin/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:906:18)
    at Object.getInstalledBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ziming/123/vue-admin/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:612:30)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-0cf7af4a","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/pages/set/index.vue 4:14-406 13:3-17:5 14:22-414
 @ ./src/pages/set/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/card.vue

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ziming/123/vue-admin/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:906:18)
    at Object.getInstalledBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ziming/123/vue-admin/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ziming/123/vue-admin/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ziming/123/vue-admin/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:612:30)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-b706a44e","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/card.vue 4:14-393 13:3-17:5 14:22-401
 @ ./src/components/card.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/pages/comments/index.vue
 @ ./src/pages/comments/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080

**Comment by jkchao** [comment]
@ziming2018 scss 没装上

**Comment by ziming2018** [comment]
@jkchao 哦，好的我重新安装试试
